# Generated by Django 4.2.11 on 2024-05-23 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensordata',
            old_name='activity',
            new_name='steps',
        ),
        migrations.RemoveField(
            model_name='cow',
            name='age',
        ),
        migrations.RemoveField(
            model_name='cow',
            name='name',
        ),
        migrations.AlterField(
            model_name='cow',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='Treatment',
        ),
    ]
