# Generated by Django 4.2.13 on 2024-05-25 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cow',
            name='health_status',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Critical', 'Critical'), ('Unknown', 'Unknown')], default='Unknown', max_length=8),
        ),
    ]
